name: UCG Patch
on: workflow_dispatch
permissions:
  contents: write
  actions: write
jobs:
  patch:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets['UCG_TOKEN'] || secrets['GITHUB_TOKEN'] }}
      - name: Apply patch
        run: |
          cat > /tmp/p64 <<END
          /Td6WFoAAATm1rRGAgAhARwAAAAQz1jM4Wf/RS1dADCbiLFzMxsi4LBPjM0SQlmWmADoiH4q/vMY
          NAcn6h2FnJYzsVcfpwuvJDIcd8GF2R/6+Pxu7vGms0a0unOZQA4l3slLicQrz5jNDaaAXWce/mIv
          nj0iDIAwdwa/GAIgVLePX2cM6AqPt6UVXAYpHVlvCxnUd29C/kzrzve/Wo0mcNfi20w3roP9e8Ku
          fm59PqMNMhwcWI+Hu5q7f1tgonyVir8eeClLfdQ9F5X62FQFNmxJ0U72iKySa7Ny/dFskqFl7r51
          7cSAZA9jeva1Eok9JNjsuOnnbbvs+qZILIUrpJAxllmdoJn7u0KAR8+b074n8kz8lhfouXPuE1ur
          CiihbWNliaaXIUz1+8F+5Tch6+AergDoNTup6pOgfmapAbdhd8cMGrEAakJcrHqekLSMG/Mra+3c
          L7WZYe6AI8BVsru4aBeKwHOZvTyfiCs77goUawBOiQNERDMSAyPGyMe+1I+DZsSBrT5MoJH6VKy3
          bV5U/FhDo4a/LPUTK04C0Lt1Uzbeg6b7IbM4bGvj5NJhz8zGJn63j5YaTUciYG2kU0V0KVH3zNcx
          fvLoviWigDaBGU4rqxlq7i3iaS5Z9LRlxbg5tLh/C3L9P2J7JzbpkT2bQKyhf2t/NTV1d+9cjX3d
          x3bZuxgDvGs/wY3qcdpqmQLE7OQ84oVTHE5z2MJCt7pMbnNoCy8TurURhLFnPs0L4Dyqmqxhg5IX
          xZhxhTHGmfoiqJGoV4x27PxAxT1t1kzzkl0qlSpBq/I6UPrqSEsxq0hmFjmUhPk2eBUhkjON1/+y
          U0af35TnV5zO2jjiB4QCL5ecNolBX1WfwnHVpXrrTCSeUYMOQbim/s7/xR7gxBNkqUKX02xCDssx
          V/ssmn69DyD/XIaEg7CTsvQag95AkC+tTaAr2aC/hcidf5dKxa8IBwSf6zB5IgXjNPe4vYLRpK34
          9oqbkuAambZX/p21yB+eyxeHvKM4jigueqlW5O5stkQ5YdOha5JukIjwS/94bNgqPqu0eBPpOn95
          /fvQYJ6T4JA+/NTRykkGI1pJecfF1CCE/crl198dcakCLAfnA8N2MP02fT/YiBzCLAv0ow12OpnN
          3ANdF3ynak+aIskSGhQG9aOzmSYPqSEXaDquT6Wxd3jLSmuiBFWMSXC0cZ0kdVUfVJ8GllsGUNMK
          QJVHLgrIsVosahq03xL0iMKufZL3hdYy9yUO4tQE4KrOdMC9Hzrdd+3srDPo5Cl6TZMNVjHUFgUS
          wa94svnrLD/FOxRnW2zxzQ+e9gj/DzlZt4WoOWVvQqcAnp23iLHkqHhIuMabKCK+CL7CbrpY+nv4
          QaxmtcWz+2ls3rY9SooneJ42ZMH8Ml9FwWHjW2ThwPPfpID5xH0fCTIqesxigNMjFwOoSFd+rtxn
          XrDOAp9tDgiKaR1CFa9AmWX6RXDsY7tRGlx22EehRvACe4CpnB8gQ97mxZJPG9mWVkW3utIFXzkD
          djSPxGToSYZW1C5x0Kx2QE323vMRhLCsf/vmxrjnP4STAFnB8K0ucCTk/TKTEoaY0R3yfdHjwX+s
          TWJ6Ciox4B72jj/ucGUp2DUa6xPdKbLHpjIiiW+NjOsiZHtCNJ+Ca2xC90bfjJ8/96cp2qVB/Z17
          wAJa/cg1kPPhCOjXFEoHiucTa/28dDI9mqbV0T4eebpwbop2paFYRqD2CjfmbuLETXpOdnpVxSLH
          kYguv97qHssF91wP9fDD02eB0XSmT8iTb/KvXZCW+c2jozT0l1w+Vscg2dsCSvFiR9TN9H9/miil
          i4NQi1phEoRPEMeWmkd7nNJslm+McGy2PSAsB0HVLRzGOXD5n9MB4TVbD52AvjWJL6/smvL9uss8
          JoTXgi7ZQZBB6U7I7jos8qdPA+dYiBdUe2QrYUsi0n+CIMlnESj1lACDSk8yYjvObeOqWSstvZpb
          i6fnceCf1AhzbhAODcdASUzhmRhequsddfYCfHieuGPJ13ghnI2c9WSvI75shiPezNIbY5ys6Zdi
          pORUBRzWG+UiN8OaHd+n8LlC+XU3h38UnqQgw4mLZYA8qa7DyvF4GR37cXIBUgp+Uy07q+k+03if
          eEBOJgwAdWNAISmqsNcxNJ1EoJHZ9EOafA9c/T25/ZQDkyLhI3/1NIUgVqhP6ilC4512+I//jhRt
          CHpaYLMUBG+lY5uwFtmBiRWwRj+Jbdd0jVsYOej21rHh2NNBv/7kQLpSWkzH9+gdLpPwR0As1EpL
          YCTlLl2n8ntXikRg8shNvDyZIEpexV3TEWp3/MaA1AFuHpkE/aYpENw/ncK+kytK0Tx66zRHokx2
          wKXmCkbFN5kwORCC8y23rXnLGHNX4a6ImkorCp5ckSEwl3jYYILg2hBkb0jiis0yq4cJGNmnHXWW
          aVEHj+MoX9ME/OAD5HQALjZfOFVUg103RdI3JdQw312bwGWO7+RaigBO0DVO5CzDreupHysBXFKT
          c8seGzmEHRxlrkXgu+xpefdHxtxIMr450lCsFw4JRTEoFVx4Aw0+htDf+4hd3uxi1P/Gmzu6DAEH
          SipjyUwnW68r9f/nwndM8/KVweqCDgO+qjnTnSNqbOcr87HfcUTHHuudsEPNoHGO0Yi+IRhh2HIQ
          K34o891Kxr/mqXxoRotAA56wYwTnTFAtA95fvCn/IAjC8lVH+HTLZzee/eSW/nB3jinwydeG9MlL
          V7DTmeSFn/Hlu8uw+kfCDxvG0o3jP5rUOUke+oJ/Dqi3zdw/wLLY00nBR9fksx964qgn2zA/emT2
          xxGoeegFIIgJIyn8Io4hl8R8rzqCdETv/qXVSwOAZZLkFB3PM2YlbgxmAvUWCVtntSztSvhAoiSt
          ej7gHUY/UkR1QUrt3qaEMwJCLgLbHEtLQvw6NOykF2sFL++Qq56V0T7HQ6SLWPgCwZwsQsmG3veF
          EjRr11mdJMfSXSZFMjDFmDqtB+wShS3DNGYeIszlpKWzJ5qC7SFqWZuiEe519+K8kAdLmepL93Tb
          omefTU0kEO1AIEJwHoY/BjE/XZZMScKDgHlKZSzuvDknIGo431fLCbTloJbXq5d82sD9+yBTdsbh
          eq+vKSlBPylFL+USq26TWZRiI8lF7y+v5jW4IJiR0xEbBBNip2o7Pdyjw8tV/X1kxP/hPNR+bDAg
          ROAiaMcr4OCe3WxmeCVNv47030YNOL+ifnpAHralNIa4SAID+nBaoXo+Bew6CaOCmQ2V18JNObtF
          sHNV2we1+7txBuOVa0Qe9jZjskgnynMKbw/2gkf7zvtwWYldAvPjbDgCuXEhmHWTS1oibWKGuBlu
          uwaASJeozAbo11XUKHmUpc+2HgSa/4+5wUk1PLnQN58EH4hIT41VDI/6T+pqZ2vZ5QWXmA8iNqnF
          uqCxiJLa6vVMamHP1Gs30B0wNMdVCnQLLrx7okvbT/sMyyfUgaM/xNkMC0rWqdTtxXvv+WHlW3iW
          +5luVb1rJ9Qe6aKIpPxJjh8deEVwur+slvzR2FuMTEtGxDrzshd7M8C1YyB9or+wZhAYwJvsL3+2
          DMR6M/ukzekRegLvQJVQ3pyVgEbu7HvPIEaTmLFxcXt/D7Kt3tHSBUs6D362Pbd2M5lGdBC/Yddr
          tGhSxK6NtBaVXEkohGbSeV+ImYRzN1Y1NosC+sMn7S2SAplxFP2PBjJq9/lv+uKq4QrhbA0zg5hp
          yOmWDbe3T7VjoUeSqh32WgsEuk1vSUD+fj+PQoPoRVZfl+yUxQbx8npsUOXN3Z+nWAbWiRxFPp3Z
          I8E/8KpcMo+iM4K/13EnlmEhzIn0wSQMsI42B8eIUYZx47aIHOIiwNHgEIF+qZPLnbkgS45vjZ4K
          Tk41ZRIo4zeQnJsKCIuUx7l0aJvD3dqqFiBkRNY8SHENOZg7yPFYr8W4WtlbyCKGNOwpDzGADU4l
          8Fiqi2mZWDILupPQxKxx4bCfbmrGOrPmxpR+tbsSloMHihR8ODfkJBDb8kf9+9Ri44/lVQh0fSlp
          saAFqQYqVbfZr0oBo/aF2E8d8OdrOHCuKGlyTq+29amqrMeKcS9XDoUGBqSXhf0Y+u9aWI0WyBQY
          9utOdWE568oqjsQUHuM4pREeNnJl+NRy5uPTaQDLaRRZsiHvo5kKdyqjUA6c9//ZpgNnWVf8yI5F
          DAUHTAYNaWvNwRt4SNxU2qRsxKm0UQdANUKrITSHtQ8Kv6R2NCvocrxvhlXd7490+z55k5mbBSSU
          HH7Li1P+i8c0p0Is9yYI2y1N3dBCYqRvBgtAMSllPmB8mPkK/wlYMsGYliNIyAq4nPcR+bA/btiA
          kUizo36WSIODri2i/DZP2jjRYkxieWH2yZU5ITguYVj7fYq9c8sM4EGxRHVx2yOjENA3KQIJgv8k
          bFSwPQWUmhoz1uhZvzO+bUjc5r41YGHc6AIfSXJANiVkFE4jnnrH4jLZMwa9aeFw23DR3CAcOLwt
          zjWr7wUdsePxlQXFeV8d2t7Te+mb5zkSXXGa20MyByiYzNc+YKGlVaSJLLx7DyLBK8ky9lv7oAF2
          KuklJb3Bk3JPGwKgv1kIueM6tcryvXhWM+GcGZkyXNaxUb2o2k2KwoGGh9/sxDrSS0tq9gybHS5S
          mR9J2IlcgyJahRqchlDUDCSHSfLjNsn0tHRmDUDoeBSHvmGcy+LBReOg4E0A4DOqS7tAWnzTx685
          nncflEmTwGjoV9OhRhaA1ysG9rPVua8Akx2iUIWrEtzlwc4KNbl04yydkmNPjSaGDX8dCqi3SrI1
          RiYMuLe9iIPcdkQGOnXRfkkteEwtyLsoAx+dIOFmBk+FeZa/fjoua/yX16CN9jsv2eWGzCPXf5oN
          6BUMobRG1WhAbn0GG2nppxDPeE+CuPj7YJ35T/baIqN7eXwejODo7tiZ6aRHa25UlaXsI//bz7Zz
          ks5t3T3tD1R5QRi6RB8RCrQT5nrAGXR8+j4K99CLI+MEDXDnMyRfBwoK7vtKl6BNNZl+3qa7XXMG
          2vnAse2yILKry2BwvQxgYvl66Kzc7nukcxuxaKCuVRNHMdHcMsgwo0ovdSkXo9PRy938RfM0MQSf
          lj8+H9jU0sbruX8gc3kY4LIOAlb3I4e0Fbot9uP7H+0qD1QVeGBLsgSO2WPOvyAJYSIYh2G7/q0p
          fr3R+dbGze+OF5kaimw1gLw2PRVXaNScNXqOoXfvLCTC71R1iRFx81jTe3lSFooRzYTKgzswcCqT
          5hM5YTSQYO2Za/XLUnXFm0GDpHSLQw5LHpizRXAhPU8fRUKznJzkFEmdDUzL+A5hBwusWI0fTJ39
          UafD37xum7mm2i5+LMI97EpnbX4nwEFgo+7WEIEteum1pBU6l9b1kS5L7umDfh6cy/mKxCedhKqY
          /HdGfE8+IAQ1qmILQuWOXQ+32Uqa/BDOqgZXG8M5dMVDl4Kz6Eqk+1jltT7Dgx3lEDVJvXT5RUB2
          tNypoV3KHroagghz2j7wHLXjqLvJMF+iJWJKH9ud4pkM5bjqoxbJstzA3sIcRxlohDARn5myWdMe
          x1Lqriy7+kKcEAfe1m8ivcPtlBhK0i7WoH0rF20bsV5339sXRxy5ZCWelbyVoI+8nyTbvPxtOCqJ
          sgfKA76shm7C3xY6rr+OK/fmCp31p4i1980JoY0riu/NUIB0vg3+S6s+DHY2Kko9oRaP1YQrT5df
          ogByqG6/OikB6obVMzwd05rbZxioCt2lNo4jh3hfCUeesiw5QJKT2VSUYB5blvCb60xxJEpCTTUA
          NGaTUS5odbA+JHG9p8KLqCUSiyAQQPbcBQ/8472neBKl6tbXVU45LnHj+afcthi0weVt/Uuo4Kc9
          DGnx8A0xmKPMpGzHssGifclcK4nqQ/lel52bkBXmsz2axftszd0geC9QJN21nuVqLWG5w6deOler
          Mjnd9axmon2Di6RUV9oHF1SpaUS1wgYKCVPO2EZrWHCG2zVCIHavK76cH43PizL4q5SENpBzYDs4
          8J1eWVS/QR6SJciNGnq3qLJLi64S+aSLujx2OiF68Gh7Cfl7JqGctHItiYH9bh5wPpOzTZrda3NJ
          46KI2JX27vUMBY+Tip1I2ms0oKIoQGfIDeZvc6hwAZjJlI4x22Dooi3ArOUoTL82DnWtLqZAiTD1
          Ee9XSHnVrPkMdu1i35rcsBdKIeT1EbSwa0kvFEGw6aO1lgNRr5b8g38PZkBfySQKuWNFcL13M4BB
          +4sDyODQWbDjWqVXbmA76nNX2kdWBorIs/FWSDgjaoTWn5MMXSprAk+oIirRdBcrbSsU816c7njg
          0KIAN681rp4fH7sLhXM8UjH7zanqP5ihMP5i64fYyTlsgTNUhOfbyyMPvDaCio2P+q5EWP0RG3dS
          ngTxmzpXcCO73LjbZ7/NE8mjAl4DTz/duQaaGP/RzaVf5iVmhPROeGqIubwik8TKk8JuE5e2qOsW
          WyVKa3IasQkWn11xKzd2z2d1/4WlwKrwIngxXX1jIJ7ECeoTlztoh04BgQieKLFMjBzmNKNqZZ7g
          QFRHTUkT3VltiBf46CUIVgkJUm2TE51m40JQW03fcVbXlwlPojng65g5v+fSlaWeL9nhYWfNByV8
          tj1M/lZPBt3AXzva+CgPz32zkzGg/6+zlgft1FYyG0W3+0KjJVLA9ebjI9fov0XBvXfG4D5DSQz9
          NYovfh0vgMroXF6l/rCgsBcbrdDEHLG2iYkSz2Tr7uwu9rqBBIk/smDsINKxv+kWL3iLXAenKXpl
          6ijTDe6LDJQVLE79jrjLNNHPolyszGTuZ28bX/W6OsSSUQIg/M6+Ptrs5fwdSwlSOI9R7dbmINGV
          tL1hmhJIPJuBtJZMUgAymFqkQnWsAahitF98F/sd716xq8te4vzgoVkedzY8pK5kJodK75MSqy5e
          JMR8bSaVXDT/qOlq99FikGy/htO8dNINBx46pFTO2OIaFMWjQ5pKbPzxHCG16mgEHhkPGxe5cmj1
          j5R/YRiyM0J4SPbcMXXIvJJWsU97Lk4m/qppktLmkwB2qYuwpxvufLv8D+1srMKcfitv1BsP+R7Q
          sWdXeKO834RZJxzEXXqdBLBZoW/mSWFnKrzyyOc2m+YTca8SZlc6Vw6k4Z1DGLFXW8nuHzubfzy1
          kFQCA6EXp5O+sSdCoV9O4egLNdG//9ua2INZARwQ9lY1n22d+F1jriPy2rTCy8/FaVJoLFWGPi5M
          mf8vDSFK+lVzH9X+TIpJJAgXqtKuWFimtOVxSDV2IkKCWW2mSZxl80+iQFeIqifPUyukqdqGokAC
          qaefznUxJjnuGoNjujgc0nVO0SRCNlRUzMwM52f6ZOPYnnpH1vQeLBLaHJdqQYsar7WdEpbxJWUn
          TUD4l3UaIq1chd9Uf5lJCCDsF+oP0Y0WZXkUMgWil7J3aXx5c+zjPuX/PuljiRtx37qYlMp1SSD/
          pbttNxRDGRnWWz8HhgNcemofCkd/gjguWevcGo5oPuBYB8FrtPTq746aY5IlNmEUGemaEC/8citI
          59K4vaoP8wjmZHWG+v5jOBHAIJbkbBj4S4qBnbvm1E4+A7kxXbNZBDnp3SnhGxl76SM/gSnr+Eq0
          R+B2kc0j4nXpbxOcutS94r67lh1bvwRSZGZ3v510/Cbq0KnaCW0XxzKviukOxUYQKtL7HSVSGGH6
          qHUlEtoBBR6CsQ/pF6EqnqQpRGwQoEHWg8zw1D+BsDI7/aoo13jI0fPkUgaKz2MS/hG27aJmeQiL
          PESqX90y8aHsg0izL47ZRWYRRPEomp9mhgCI7AV+AdjsBX3nN3PGRmuEoh00j6hPJFARos5exOIK
          lMqCACPuLhwuHrOfevIn2PzWlRrAJQQ8VSC6eEIZ+rytsk/g1HpH/gfrn2N+ljHyy31RSBL9/EJU
          x1jVjNj71etx/f/I5147ekg02d6mftzOc74cWdgTKwli6DEFYs8IbRxdfDRiqMyJja0ZIpX4i29K
          k/w1Uho97xSL+jTSFiNEpwcm3lwNljZYnbIKagCS8ygGmzbEHV8uOaFurlczIjsTjH4k9Ie97c+7
          nVThPirupVjHfgbeAWl1WuR586ET3G4+pyzZX2N0JSxpd5veUz+MJQqNwsjHwh29uGarn3ggd080
          YnRUrEISipN31dMvYayeZ9Txwktz1niO0A8gNC6ygtH00shxTENiqD1VJGC725Gjc3j6ga6uzKzp
          rTS6Kh6V3wcB3ScAF72Njmqp+Fh6bqZUXr0kaHQSu2z+zhXDq86iYn11mXjYkDxQcZvYr+UAQ1sh
          BRzQNRzMHr5IIcbDLwPjokPdCjuVo1hCejGN/Ui1Dahi+RV9tXM5sdwGk1llCH32qMNWSYOMc1OH
          Nekk698JvyPfty1vC/YNgNNaRcyalAIBKKF2tXg00naYAfLUz8LNI3ZbA0Hm88hV7YtuaSzX3zg0
          uovdnYybgYZ1L1wWKOMKbaaxKk/Vpo4POSQKB4iRPehpsrr9zekjDQxzWtw7CwTzoU57gTJ38X47
          1/jjPzfQAOacI+GpmjJ2XaVJ35B6WV5beInn+PfUVwYwbCk+GoXEG9tEBjkzeAMpmsLPZFRx3DtS
          MDr24k3hXvTAMDSqZJzAHFnfu0FU+wBTZcQ6tPAOu1adlGHTnFhpXNVhglvvHUT1WOW/h636j94l
          0unVRFJvjpTnfH7vNwEIHbZA3NKVQJW+mHCkGJpuH0gkr6u23NPp//OtkMMThZF6C6ViL+D/WgIn
          dG6M+nrN/Sqv0cUdw+O94V+6sQZfrVQMqJ9HSKO/ReKIIGFYJcpcrJAmERWedOiy5MnUcenrxoD8
          ON+wXg9A77uFH9sYxY3Oz2DJzJCc4tuI1rhHr4Z+nACey29S6O8NcIUKVt6KA8Ws5GmoJU+0ROu0
          enkYwm1kc9k4O6jRAv3O2KsitUSIwcacCatyQHw+fKywbe709rSICLyADvm+tQhIDQRaAsDGPuzr
          Sf8BotCwbAHAHNQqgvnfQMXFOxGOFWNLSO4u1wooNHNyIvRABbIVJnIxSZ8dPxmG098MFRiS5hwJ
          ZVTVwbtIS83nHl5usi4hGhBhfpM0obfTzyT8TtSW6dORosv6+amrf4gQuzDIvXOCFDxFG+5049f2
          MBcPgIotAorzxig0pJeRcug+OsgZ03VZYkVaAqvYm4hnsrhXN8p2D3FQp7Bc4WWUlinqSpNQPwX0
          23JNf87VAsKdp3W0Qf99hfGCL4F/suQSd0IvJAbf4cjc52QH8bB4uQanCPkLg7UWfpedSharsn0M
          aDYzP7rnk/GN9AorZnt4xuXIl8Whi4xxuFSbqIVMZjtmaeqcdM8ISGnDIUmxkW2XaSUYdZma6xkP
          c5XjaUFBm8SV27EoYdEGH55zFq/uL6uJQaH/jX1tDfUSXir4DVlRQhkemqs9UtrjyQfWpyfie8zP
          tjLDkWhn844Z29AcjX1JgkZvfw/PP2RF8lunIAxmTbkPjMN3eMdi1nmV9IN/V0OaOoc66IiqXBVj
          1H/sIePBPmrs3Mw4Nmgjd++X5+q/6Z6TzGqPKG4tYMMfTt1EFJnnSo93G5C1QODZmG4DDrxW+Kh1
          RrVxClmX6mNnlrpfaBAeutIlFKK1TfXAHfKkn4VcH0lrq8p3WKqAq3jBPPn/KNmxiuQcWeZCsggp
          d9n6ySwqk/Ri7ieoHlO+wZ3U91B+QEydVJoqB1VvIy8rP6NXp1NFtViDvzIqX94YXa3ErVuJC4B6
          VPASHVaYE2CAoUKA7CYYgDyo8oDabggV0X4rvYebMUxyswKvnyMY5fJMnoqtAY71UnsQqZ3AtwoT
          iMP2g9x3haUWrECWsXDFjMU9elQqLDfjIx3q820exsuadH35oENp3Vvlg+nUVtd71WqRFAP/+Xg8
          RTMKwuTof64r+Bqnypnc6gIGMlkHv/jPPasu7rIDFZUB1waixfOS1+xgbcnoAqbsSubl1ur9w8b0
          4vcGfJnsXFho42C8McGh5FQgFft86jFB99yPRcf2R6vpuvlFvTMMBDAUDEhe4daCxs3ea2k/1Sfo
          Q7f+wwwYbBgMD1OyTDh/OifQGW/pIqCh+oYmNTgWKpFh1cKtC/aLmuon+HOR7UgZO2qzdpJlFsQe
          WN6pflaSTzg3Bk2YahmbvruStzVBqePwjZqNzak4ZKrW37YUvBYlin5lNbAswDGRTpemk9sx7BjQ
          gAtRkK2OByC+k0QqKTrdbsK3osfh4ixw3LFKVL3Jq4ktaqy1iDBjZFSHnSv7oGJRj0bfey8Vs37d
          LxUYmL4lxa92IWMmRGyXq2uaHepbWdHv2WQXH/of/Donj6KY0qAJNFgfZpak+cB7Wse7zJIaRcW6
          PHuePPn3N1hvM3yJuYhs/sr9dT6E8QJBkIx5tVRUZsbGgWQBrG+ymvNMNxxYbGE/FGzvVNiOiv1/
          yf/ORmIrlfNF6jku/gWENJ7wh6bwy8z2HUJhKQ37wUW95rugEq2tp4MPpYxGx9IHtYWfSy2dGRea
          An8YFA0wJyVuHNU8mVcSC1HrQjXvrF+UzRvOoULL83h3PpOu3grSHWnINnVSYKcgxSRQTNgByAN6
          kWEsVeIu1131AeTueub/74j/x4fjdoJL28uU0k4CWLrt9UY1wCcyGzPOSvFgyXVmPynmzXONVul5
          ZJkosiKKQJ0iKxto9Fg1CtPygve8zTHb6l+CQoDuYzS5YRnQZ1uFSL0rzw3dI5BLbqCPeQOggg2y
          S/drWJpZ+tPn20WqKTcXhpBu6TIkf2kMsA2t7xB9flz8A64HfX30RibEcjfE3My04agwUcE7TNYj
          Zk95fJdxpwDdkXfpkVjx4U184EnFODf5Hyv54X0fWkjTIvEhv5XW5jMSmnxOtblVuPXjne9pNWy7
          yS8vFkDxnj76tS6AGWQZwgCVtdVNDMTdZO87fxrTCqTQFB7XIlKUtafWgiv1Fr1jwD8PUA2LyfQ5
          +bYfAjLIjG9U0YviCYhNW8Zd3m/Mkl2ulZ/Ks0GuIkqlEIrzMUUltRjIEZ/te14dVoOeHmZ4oUD0
          ik2XBojE/dSiHN9zb+hrtFnBOZOuSvpnGIit25OuIRLN48NRS8N8KsGtFYUda6mAHYgAD7XY4970
          TfMgT/zMshfjQ2fmYbS2EEzKTX94G45gYE5++BAB9pGRGk2eYGgTfjmJphiK5+fbvrX7wRDkoCwq
          YGuqu10w9VGHy81TfAuLnhe2kAgogws0FlyC5+zObMXh6SMyk7OusZxRe9mtlIMR6YlqNDebOKOm
          HvEgMzY3KtIFhrdlnMRH/I9dJu79xtelwRFgF1yQf+GjHf0Qq86fj6VuYxs9WltW6W7UlgMFxSdJ
          JP182okuYjCoVYx7z2YiL9e2GF2AneKPVOYfVfGFBsNCgW7qwJ0LQ25Uwxzs1KpU5lQnSPbkNsME
          SJmfxqjMJZJsgO5yHRpDHrPHCtqdSIUKPNYt0OCVA0B/jTM3BI6P5/1af21zM07uBn5fOlxYMRV5
          RTGgrf4++KlKcBUem/oeXh7YsgxyYXvKZzoiO9N4+Y9rgYxd1x7GsjZiRnVCiESE/cmKzap5eQaz
          lwclJdiJ4/UBIh9DTklaCmCxeaJMEhrXQ6uCmTk01JHVE3IMN47cUOihu2RbfZKE4Cq6PBRA3ifA
          k3fwlg26NLiaPLGW8kg9aa1Ec+Wp8c646tvteuPrIsQhhhS2YCbunCJioSV4cskGt+VSK7Qdl2Z2
          48KZJnCrPrB1HAW+w6Vq53X77C6aG6Hph4YTZSS8TO/RLEL4Ew8+5UOGqzMmYvQtmnRIobf/118k
          HxRQR+NKYkcfQaTK9HzvgJomcCvOR2TLhOX/kkqQAbwT52oPHwr4dpDxvwkhgsTnCGApkhsPT96T
          Pltj5xvDvtn8aBJaitxf547fxd/S6A8Z+cq2EimWST/wIdZSfbN4U8xadw5tDFgQpyYQTz3sd3T1
          4YYao03kJlEPNQjz9kK/MTOfRgmzLyHhloyi76AecZkaZZoZB8x0QbxQF6CADjeRqGtYYGEbWw48
          dIIhR3YbA6djHHT3E++1tv/GSC0SflHqfJSyW3nnyiQHjUvbiQzyH7l968mGOgANhMjogh4jTpEq
          1ob75618FHFjF0Tsuel8InDQasKgt1cPaDgpJPxY6W5tMNKnpkx6YlT5lMDinZG3ILD8We+1JnRU
          nNSmolbCmHHcroU+UcrStSC8HCp+oR0WrduSEz7foIoGKOILyMcpZVwPfsZ5Et+5xSLX/47VDa3e
          kq3ez3gqcMj84H2s6w6bMHgs3hhR2ohzcOMgWwGCefAnn/7To+dHUGTn4sY2PK58cJDALP1rZwQ2
          O8XlgugoI6bgOd2Yg2lsdO81D+W/dbRL6IWQaEdlfSYHGytfrqFsd+gJkS+lokU8lq19t8wylUVY
          LtWSpAhwOCCuTXJdQcbSXVwiafrGogt9V4osFDNGcVXgyMXg/irNOO212XdxnzGIsPrTOGHjezDo
          IvCq+sOd2FdKd0exiE4oxyCYeH9v21+20JvJ7hc9WMTpDk7t4Chka7VVnqkMn0TEXvmlFYSe579v
          ZIqhTiwxEhA1Ya6eHSc4zuA6taNDxz2J/7jyhkozSyiJQR/6rcbWWsi7C/IZCnPMFWjm0mZMKGwK
          rv/7bggHscrPfS10Hr6PZH6C5/Oe586eaylv1BYXYsNlBqxjCFXYv9fm7MDR0ApzFKbcu24G5QGv
          kD15yrOpspBrfqYhXj9UhxiUcyxifTJgb3pjVKtlPPGwelYYT0ncPxWLD9Qv4W0rEDz357N+Fo1t
          aeLJ4KRXJfn8ke/ZhcCoAWIE/VvHp70JAgLoSAMUQb/RFgVan+YIEV2FE98RCuwuBEINnrdQIrOf
          J/qWIFk9LZs8IrwPSLGkGIl2sZi53t1bxJrA7ngmN51mfQmHg83ihpcZ2/FETUq7CA7F/lzV2gbH
          rXJ/ScYfCUU8eucF067dyxMc4pw77icdcFUVGl59bZV+MCD85IY+iHfztA8scB6lo6O6G1C1Gw5J
          DngAcnKNw/emrWM/sCMnE7gldwNU8IpZsIWSctotO5xKUpGhRSsDBkNaEmfsKxzFzg/F6AOdFk10
          4nPsZlMIboCbYwuAR7ilGfYBIkfvfT929y+e0OTFGe9/oPDoRoQo8IRY9VlWbTNz/5ZSMQzdzhq2
          PrStdFgeaZzBkUo8cQ5OvGHo+zvcOnnTuN1ZdXAodYmzBCUd7b7ieTwS4H6GWPfPur2+Sq6daYmu
          WslterVF8wk1mYE5gbT4YqUI8Mb+18xP2qlObU6YUOIBf+fSrt/IbnZs+HsekIlb+W53xHP2f5sD
          ssh1tcjbROYmzDFP4YHitbIChzkZWL2Pb/ZeiAoLNrHCkZO9bKqZToMAzHjy5luekSX8JBSpm0R7
          ibx1wC7IU7kHzE/mhEcODQNgFwE9vpnvZRHSmjAcOCN7OH0rCi5hHqxvg92Od8LNwvFQHv7/oP28
          CwMsHPS/w9X27MoRTbaT3zUyEN/fI6KaAo9WAZeym0EszvJ2CqSB1T8zD9I4e3YR3AoLdbfsxu/L
          0Q/rwAAubpamIVBawJuYrRlcDTE4iYlHZrVFLLZpOuDyNmFa3orubuG/PFUwojM9ZTe8f9tv/F2n
          54RJbyDZrpU1ekrjkJBGvsMx8cG3mflkiLw/9Ns5NodGkStCWXqwsik8xcojGr+5tETjJCeKDZDG
          0huxDPULxCM3XyReK0tEZ59vDyAG9pkgzbqyLEvETOqOhcLyLGrR8+jTjyaZxjv/zXiIaNP1pbNI
          ImecmDK+DSX+OR6yKsgdTZghW+7obSZui59LbzXkmvBUgUQp6VSRi8CQqh/vWdyldtbJbC470ce2
          YxBRmKrVPpi33aNOwxhkXnWq3zRP8WyB/Evng3WtMIMZSKHp4bJKHebm73ktWmymvMAFGwRycW3f
          yR/6euwezn8QCoIdhB8JFm+AflfJVNs/ijTFCh9VOvTr7Gai7kcIZ165joartDxqrGRCmL1+fX88
          C9MmnuJ3rjhZ7U3VjWDJnqSudsYzyzNtniuoblMyhN3shTTeIXvru/RnQC2S2oF35zEOILQMRCmW
          73nrbS/99WuOPxHWANVFQLPThgL/D9btiMbl9cdrvpSxlF49iDN4oXmCNsdizrqovmNbKn/yH7m2
          Nq5WHydg/xErkLUhwYnkQ3vXCZNSv+2DHajMjqX9JWK/+d9xUJj43pShNpbBeMOqywT2lXUuE+hc
          ZiSdbb2YaKGUDKJ1M6ffUB6336by/WBboiSC7hiNIjr3Muh4AwgIRjI/FfbwTGsK/uT3ZU+j1iK5
          aJFC9JgQdjjPhQb671xXCINCbjk3VgMTjd+J9oTOI/HIbjRXzQNKxCbMUgx+SslHKhliW+HC3dxB
          HPjo1UneiKztWVdcefGZ72duJ55gqtGR+80cW9TPTBUaaxPIgoFSnbvGqt9ILrdU6yhACL34MKKr
          XbOglbwkO1nbX8o9fJ5i5y3mwRJMzwxjeFYPF/KDZ1y/UM+R33oSdOoYOWaA7ZulIGhyMR42+M6A
          lqM9lmjbkxY93nM1AYY01ddlQbJ6rJODjZ4aqXV9/9kxMBmnTADA7Si5JD00Fivn1hKZEWGHWnGV
          gcybpFdKVbu0I+3m0Th3LarKkVL5CGsvf0sFiE/Cz/qQN8T763mHmHccU1+uta+CzUi6Ape/paPH
          Rnobm9g8K2TMqLpuGRFJ7IrjhiYfxZXQLV8+rC5UmKaePVfElFc4Oyl7zZ7wATMBgUV704UrTG36
          qSFCOQ1iY5Fw+e74qJJXxmje8frr5SVATbDUgeLdtrcYBPw499WItrBQcU2N/2A7QCdgacmpr+hw
          xJFUxwK3RIqPSC+foxsBIrgQrqKAGf1zE97i6VuFlZ07EkuOpaCOhdpl6lfgJAM1nIf2JEkuv8XK
          AorZGZK4AnEizSMxfI0s4CPDDl8nciX21J8mUN8yB7zVFtSKWwtOhZPYoOjhhU3qJNxyEHCsjE04
          Z7yKuHxlb0S37zHiOfVyJHaa7ftI/MnHCOADs49ni8TKNfjh0O0XCk6MIpG4ltLiVWlCYZSez3bq
          NAu19tVRnO3pKgvBNgg3OpMRcHrZCTwD7GwQmENvbpz6JAAr5bULKLX8SW3Ar0lYqW5xmKiTs4vv
          LvPI7jGcPDXrPzD+mMnVCRnAouAQy9/hre4EVo43ek+RVHg02d5ZGDLgLUVjNc/mKRx68cpI8sAP
          hSOdXgB0++tHsEbEvu5MqKSsl+SPzO7sT6xZLKDvxB9NoahifAoYIgy2PPqkIRdvhGegvyYVKq8z
          nXwSjtKxv80LYiCNjhJ9xV2c2q8ERkeuf26lAPYN6b8BF4sNtXeIqyQLNPmZ9hYEmp1oBRx160Yb
          Dq2SXuAn1k8O9+/nnn8RF/KXkUi+x2mzQiz3vsdZMaQa+ovmgZAuWjT11v4PfCljhJ9TB/4kK64c
          +pf3y50hFd0o+/xLmbe9VZji1gSxaD0Et8+PSeNnUhyCqRa0gWNM30kWN2LWn0V1xuNiH+RXsL/d
          fUL81fmA3rbITRcOf56Adfbij5JuPf3JBlhN966rPcizdsrkl8XFbvJfZV+mRu4VNkZV92xD+S2c
          JFe2QgJSZXjc9CkgDC7Pf1dj8x4wDScw/WlJiINifus39JfJo8AbK5yMa81x5KLEPnxxrJKQeY7n
          g0esb/vAVdaI3E9nkF2OpMe698x2E+04WyS4Nf4U7gZEdjVGKuRyhpaj7ZM4x6sOwIgWoZkyGZgK
          FJbuopTq50o91zgUubULAcra5HyG2KiKiYVM6jL4sUKzHugrIKLfl4PTPh19iF5BLA/ejNV/vsyM
          4lpMptC9uY0sXU3J/CHKZx6pAYMvC58+AV1FCKNtxdl48zi44OTHZb/OwszH5GOr746F5CjLrYlo
          CFt71NM1ev6yndVy04dnhMfVndxclG2a3UN0Qs1zFrs0sQF+PtkKahR5lwoV4k4eTrwxDf3/nBZX
          AYA4xyUqJVJWn0ck0GSXWCW/p1e9GmvMeraX33/I9OLmOeteAZBL0SZMf/rzOUJF4ghRCu4tLu9Y
          35D2jfFY0UKY5gOnLzTUfZEwYZbRmaaNNeYFf5JjzgJDPqsgaUygs+g34ByH8e4/Dd2558zi70SP
          xWB1c7jwhgswWaNveA2JG20J1Ff9xJ6LmAQ95L4m72CAOfGVEwHMhVg2AG7dDGif11h1B9bzCFDM
          PB/BlT4eQG27/MfCH69/rM2/x0IL+BCTqPBA8AHjyJHiEge7PMylgqENHFD+zG175eM32BmLKm/Q
          /MRHvc+osWgu7mpnAxx7Eec0PSQrMGmVsCF7oOyqbmCM5w7BnwCGXXNhUgBQm9f5M41wwtNolNhg
          c/UZHD0fI9A6dkyEtDcgxdYJ0yCy9oenp0gUtI0rib3FbiE33ZzGrKJyj152SFnr3j8rrxWGe78K
          b+ezFnAgMV2DkHAyroXPF8qcIW1y2aKdMiIfVzHnFqTaegf/bpyEBSgGdZsCP9k0nuSMdDtlVJgv
          YbrT9vuie5nBVBR5cWLq4dk+wwabLznngXDL59VWSTXoC9Ef4Mte/FmGAElZgHAllYmmpotH6j4E
          iwi/rkarp/uhAJTIqMoOsfgApeMtvdABSbyzNXiuOrUWtlIg+udKtvKnQr6U7vqK8Qa33lJH6M+6
          9gBXgO8EQNAqwhQPHXNk/v0Qm+r2yUHxWDoFaaRJaT9pAH8xk5LWOrFLMzZlSowBcs3cSZuJ3XIq
          VgqSs9REK6C9Pcm2tZAsH78/ribMG0KwCEDz7j3RpDgDSdcvcg+K/p7bfwVO6ywLQR5NP4lUeg1i
          1KOPqLbsoR7y3dl4VSKpfmYJ3FC7iSrLj+8uF8hxNG7ot4hFtfFOIJhwfoU1N03Au34x1Kh+gkD5
          Bo7HMk1JAjxAbIn4w/DGzJjU8JLtDl9TWB/L6JXlz9LcXb0mlGeFwql/bCKPH1m9hFG+NsxBtweM
          Q6kZUs3kZzZB/2e/ibyt0gf17uYns0qLFUwypCXvyRzhJR76Gylfdlvjv4yh8gEDRbbSpg5IkpPO
          uZ0LWPAgPpMtvt1008SBwv7IkTJKyPmnRVryK9Mqa9dOljBvlYw9vZ2eCImTSLiCgfvUK089pMrg
          8k2waEs/AFIQcLRGLJGw7Up0R1PnMS1Fi/eOTNUBkJXevObBHJIXzgIw0m+J2XLS3Jt+cL/Do4RG
          PmPPmNZFYHcm+YHvGY+rDS7YRyKHQJF0egEdO3803pPRNSEpcwoc1ZzzjpiE7R08WvW3jiDa8i+1
          P4K+ww61dvn5M+48os4fTzc+IKoqpVfUTGCEokc4/Pl3ZeXNSUUQu6YCGzjZ6qH7hnCXocA1QVqK
          WqfeGpbB0wAfnRde5v3E3/uW5+I6o7NBI4OTOk+wQkUAs3O4WXQvG7HXwkb13OmJVxgOTPLNWF1W
          X6X6ww5B4bpZxUG2MKjA98wPB31lnozPduwIuHwLv2dX0NLbHrlJNLAMrDIJT7YsCm50y78wYBBg
          LJbwhHaOK0jOI2htgadbBXr9AmNbvBZO7tHhl+jcEvfkCgIa/vktIOXHmNtKxcalM/1+p/Z2neDO
          u/s99GaFpIsCI4ZP3wB0i9HjL0aftnNqkuNzdoZJ++D2N6tbSqY8IMYFDqG74u8HrOZp5Di0U8Zr
          uem5uNDYjlAHVDHR3Dqf6IGLGjuoGUxBx1JjlwXwJIifAgdRGqGz374hSUhss3HimyXJykXgMSPE
          bRDxkV3RjMXGszuH7g+yVtCKLm6F+zgITbSqgTHYpKqatxDqCd58iAxSAuHSlKWI4FNAnxy+7oj/
          HnkbuRL4BoA8SZ3XGsBbVre4HRyncBVZ96Z2lkKZarfKyflJiv2Czy7ZrrRU+OGVzeDO8/L+DzpB
          WZaeYy17nptc8o/HDdr5mhsWYenXlajUrzhQaqAYlUXjov//h/n5cHgtCI2/vjkGKvJlw1oZgI34
          h5+AHv3hWw0AgPSJ18VFT31UpKjmGo87ew/xGaD+fVX7TfX4gytqMZueV99uBU94QVV4HgAM2L/T
          4SNxXxY1ehKamnY/O0un00N531WM3oK8AWsae7INN0FcFbC04DMC+Unxsuwl2ZTaEJ0ApV9wXElj
          yVts8UQyfMioBnNDrt+E/1Fsz0mQDFs92E55bAnObTuQEGN81q5KmAN5a8zLVtTMlQLknc/xWj2M
          nCgXdKkiQ+rA8QJ6yuiSTC4QYgqQ7KTtwuSWtT4h2geyqq02r/jCM1KPxeVwZBGRC0eIARL5ONjh
          s5GuvDBygj7bd+ImhF9MrcoITblIxf+R+OBR1Mz4z9c+GsvjnBBB+E/tk79oYx7h6e+UfRewIoM6
          boVy9KNVgfSLYxwLpC3rzOxCp3n/lQliAbALfU9WvAEJHuAcl0WeJuqnRWLclUg4cgFi5QNjiNaR
          30i2XG/ImnGAs5L+BGX6SPtITr7C6v67SRy+DW3FKMueO5wdj0I0P9PWLQdsE+xU/Nbpzle8klOl
          G/Pjywg3n9cboCKueReXSjYK13nqwCuxuU7caHXeGMWwmbCVFimtRKF/wBmypuLBIxM/mVWVdbMb
          v9Hr7FBoOSYOs3zM2EHHV1R9c1GZjsE0J6swbx57bP47u5A8XQ3EFDiKVUytYqEQ6j0qhoBN/+Ye
          IH4LYu7kSkt8DqfnEzgLaTUKtkiCcDXE0jyeGQeQdVRlN0f+k3IdPrVXeEXQHU1BmthYcAHQVht+
          bp5I10B8W68R1yKm4ox5GLUfqhkoBuHRh7EX1ZiCm6K7aNG+jz83BL5467uCPgwaKQsyzmHxqeuL
          qaoTRQMl7ODsotoHRdHmJOjlLAZ85wBJw4Y2kVVJ117RlwIZXyKm1l7UBUwTatv7I+pqNqtZKMdx
          ruVuxE25eloEF18+Bpbr0WRfbXJMlyPe2MLsOTSGurmTQOZGFDBAmOHG5Oc8vKudLabI+ETSoLwl
          3itNdtiOACN30t4wVeuGzzW+bPiJ54mKY40iBVDGwMcU31uk5VwxOZ8ZIULYs1pSFG4PC0yfiMGQ
          D6Knlhq8GRICSvF8CBrM67hf1t0Ug7SX+PYj9YBPSeICWNVlrVuURJle0P4C5SLESYCNbX9iWPeP
          C0G1j8MJywPE2L/aBtqIsq/4W/KcAxz7W8jthZEkA2P355xPj3hMqQQr8pTvedBskODvM7b3rXdS
          IrdU3TcGgFeXfOAPncDvJgW1xV5Ioos8tlgbLv784N4dDEGKjxitaL5ocHXODYKpTa9CMrozZh6y
          sxe+oTFpcMh7pRmmOm6fa9iJOFDZ4iQIFC0MrN4dSj1CIJOq0DhWnLy/OS80yDTZGVVvCoBtg5kR
          ZgV4KaXe7/4G4j015ewJeA0KiuFRcBv8tckqKrfkeYuPKmcuM7hMcfx5GHo0KQpTzgNL6ALrQ6jJ
          eXsJ7K/3hGqKE8MUV0sAqpgNtUKL5ybXVP/Exa1QER+N45DG20FZjpJvXDjVKSzeouKPbiwVUpBw
          6DlBeqo/IcEXKI4akwJfCtby/DV9g7qNWWWB4afux8V10L4Stg0KJECC3yQmz45V+ty4zuP9l4iO
          d8CdSLpN0yWkzqA6fvUvIg3u5rvTs3BLdCvzTwEQMSb8+P5/6AqyfMjZBlZZG5yDtV8+BXaP6YR8
          DPYw7RWjKpQEsn9mzo4Qp52u9ghOxPZFJ7hvhMBEDZgweb9WSHl2v0fu9JHQrkF2nBg4L3pbhqkX
          UG3Nmsi3dmVE4RH82HFhoTeNjCTWCUAcaLmCQ+2oSfDPRH+b1o9ajBuwhPLNX8TqXI4iQh2QOD6v
          d4ZPpAVKZqe8v+sciUgVD61iv214l8LNY0ceN7WMPcfMoGAkmkwjYSqn5fEyl3BR4RenSmuEHPKr
          xVqgvMloIuiCWQQ4Zh2BagktdQMRD69alesIuUUE/4xA/VF3b5NaLwgK3QMWvl85vIz9f5TIy4pu
          5sQAzy38IehOqjMbKCcEYWAWNohHNvg2N1NGaXrOvujwoD7Dvo9fk4Jw1lgpWuqIrOPQSbDUlwCh
          LSjKv52EgCeaeR/xz9jZnGgTOS9Vi3gqR2tSMqvFhGkdPlSLEUgC+FM+wTyPpchtvshOT9TLklk7
          3zlUBzYN/fz6tqJW6jfWiU2JYCv0VeLqLqEAoAOiIM3N5dSQmNv7ufqBh+LVeQnanvcQQe0/D2gf
          hsSjoZKkIOHo6Ce49ga6RmI6WesK8uLxOMR5EPs7aGUhDA56whGbJ0kgOu/7wXllVspWY8QUNuYh
          Qys2DJD47qxQpPBWcuDKGXczbireF2dOZW2tVqgvqvv3NTuBxBkYqOIWzfRkggU3+9ND603r2JYv
          ykAFIRw4Vaygrz4O7OygzeEYI5G6bY9bJrKc0wxCN2x4WmmR4S8FhjqzUG521pUF+uGT2V8LHcX5
          OspX8LPLSYiaz19tYpmhHthQvnDtMru9YtwSjLwe91AMqLsI+ji8mD0e/slFLXWQtWAAjb4+GjKu
          1Au++3ubNmK6rtzxMx1mqhou+RUaiM8G2uwBML4J7AvPVTrcipf6U5Ytw2xsADRTB2yR2EYl8ZGT
          4CS7Ty2iy4tXB6HSdlUXKaRHJMvjLRwQ9OdUYqGDIEhyUu+tRhASleTv2f1uIKwEPcpqBYkkr9H0
          ULNEpy98wCPF+Xbc3Sd9MFUtSAQXYRddRlNrydJUnKbGUc/5Lj6NWM0qP18EWBFCpDvKcM7tDgKe
          yk0USLQVbCsmKGsRAnRi+RN0U1gCtElYKl/IIqx3+EHsdS8kFTjD74hfnyId/QW7Hi0sadPloSHq
          fWOZLYKHWQ/CUGrbStrwtrAn64en97hebREUFfxuxnjgWKKhypc60RrEuP+Jvya3AaJCbjVZaMfU
          uzAXOuPM5jFUTUCRAiNqzAzYXaHwcvyc6pJiU+t9MBvBYIJ4GLnrH8xdLbm6Yz2xI100pb+Kp4Bp
          ozYylodjG5K6liA2O3oNvfJu/YfVRL0H5Lj2Y60ogoPe7HZ7GFu/XdDQKpWBajQe2zOCMOMYl0bB
          HAxNzPXQP2i+x6XF3Bf8yRBODiPQ5EymHq2g+bNJ2etudABCr5qKo0zZJ49KfpMNFGx1E8PEbjzx
          eudhhoRDRzKjGchepgxAXFYolZc86RHSRZ+j2Z0AVjmC4CkUri2sGpxBWT/f+MEWAsOe/JDJjAl5
          OxHhlfsGHmqzaoAe/s72/g76rZE1tx2n7rvpRaQDh1J4J2gEHpUfN7803cteG6w8KZ46zMWDcA8L
          pm/FT9rZjiXmd1lxNSG5osJGc1ls4uKLDrjBH/vqkbqw7kv7lYhebBzehafCGCY3nc3m0oDT1fu8
          IV1MN3NiXOIQxZwKAkAK2q+fzfOzAYGJIGabVgqn9JdGLOBnOgqT6aW0B1ATURhN9oeQ6wov76CQ
          iqkV/wzU6rE99MCy0KVQzM1dVGPvCwiqNMiuOa6ECzr5uKErNi8lsH8qufAhc4OuhG3fCaePGJzY
          lKlMECHdxtQnSgHjmrnsHkbNh17gwhtGEdiYi9zvDnPlPcsPs9PRLxY739fHZSmwbUGBsxj4TE+T
          QBzlxB9fKh7PrZ9oS5A/fPtY7lap1p2WYhcFWOq1cpFAdiR9c4k1vLFP8oJ218FQnEaKNOZi3ww8
          ig7LHAq5naNbjR3gCM/2Kyknf2SZ1YwONWA3+a1DWtSgQud3qB/3ZaFzWBph1a41A1hcjL6TACpt
          iP8V80jDeHIagvaLGQ08Hhr0CY4GqCHVoPLdAX0B043yRpjcAaFQF3xnn8AUurMo/Sz2CK6a1JtA
          A3i5/U3uMBzSu1K+Mh4AR0m0LuJ/c8ps+tKezXFLx8n8cki8YDznGYt4lK2/0jUCCzT1N4hp4XPB
          bPPRm5nuRfxj+8SRz+5rRdnlcEdmZ98v1CpEQh8W1usNcIzjtylFi1CBufW98d3LoUul/bz9AF07
          TqeKE7xWZF9ZAytdymNyB2AVCe55g9wLXF2bq7X9Xff7wSzwuK9jzL/RTlG9MCw5brGZX9lInPow
          47ympE+jNO4lbOyxChW47IpAfejr2kRytEQuJFGtyXfHt54oNXicw/ENYivNhEkafpjv6SRPkTnn
          mWtsT/BuCIJddZX3u8LL5tpQ2+6JQElFKbav0WFMH5iAeEliNi4/g6BhdsTExs8kRxemkRD3YjUZ
          8JWRH2WWmTfjtxB4NgiElcrcrMKEBp6uaa+60vqCHiUVQaD8+QbCHHP3L5kTSf/wkgTES2rX88qh
          31rin3E/U0uMBIFgz7U+R2hABqGzouMw3PfygTWvuM9fmB/7bVTwNWKkS+8x/zdZ6WqT+EQyjqbk
          FjXDO1fVCbXFY1c3t3143OuMppM/3vxhf/YsoFgOzngd0oH2zQTlyPzcoKbOqU8WmNSB8+wJqjdB
          wRrrcraM/eYITfWnRjN/nczsRlgqNwHAkqIKb2xZtraOHnQeWIZX8iUSye/x4G8s+tXRzTtnue9d
          3JGCJrJn+SylTcJpbpNJxxDx4PPlmDPlnhuV29c+9aIVLUIdcymSJWnUsRH3qcOZR4gd/749A5FZ
          rC16ss6y5gOrsaA2XG0OB/kLXu4/7PFQFF/vgJ90ZEuUtD8OxnSXUBY3mFlBw6MOia64qevhMyIT
          PWIIcRiv/EjlBLuL73EEW3HDUFZJVhE9ObP6+H6EyuO5q//pSdu/5LfHAe4ib2ouKgni7YTUlO5Z
          NKMMsFmacOcmapQCKcKM5mRVoX5jEW4vA6RVqbokSB+h4f6TAhUVNxVHXqEiUV5bmZG7SjkaAkLz
          B9pU8p2K/o5YuZegejwXU3mjM3b2H5j7y7ONdCPBgd+Py+gh7Ly73iRFYpU6Hi6N26a1vV40Fr+R
          R+LdVq+dyodo6DlqYl119n7QlMvisgTGcX8vXxmE7nXfMCPR0fTKxmJtwaIIjxeqs3Z0UdyTpPrX
          WmfLhTOqzImfk2kmHtGFzgvIsD/AR2sv1HFFWLR9A1W52YHuQ+u/Ecth3HKpauB/ObzfX4Eq501V
          sdA2chkjAf5UBDMrwa5R4rLQvt7falAHWYFouf1lsj+yEsJAigcsZisfDdoLU9mWsgxwEPWZRVQt
          ElqAHkDVZHRIw3po1C1zXtc37WuiJhWUG6/RdjmUKAL41C8SqGmamyuqNq0V3DJZCazZ/x77Q3il
          GIBHsxOzSyzE3Lx1G2/n9K5dQAaoyaujd3tnUxBk7Qk3vwzVn7Zicvab6Ntdw0iH4dDyNVQQ2As0
          atTAezqhOgQMd7mlR8OrMFjynYOJAcelP0m18fojqpQj6QTi72VmHzAiUUdk91lNMHbBM238YXwF
          ZEdMHAxFN0f6rTbCw07K4+yOLrm00qzfuIhJugx55Ss9II1HpVRiWtHz9Hlxet02CgtVgjGd4sx+
          sgkl7MbTQ7vB9u/jx85/iabiENpQoosDxBNljUdGj/uWx60xGDt4+ZVBepSNwWHqEZWy/39qikGA
          npZsh5UMvXTE00YvKCfhjV54q+QTfUdA9/dZ7gfzHspwh6s70r+oIq+S/fwCdNhXBWRtI/FOLxlH
          8qwXpEnL6dtKOl0tgPLN+RAwpI2dts2x9LEJDU9I4zBZOxrIZDiPgqW8mydTOBQnksUB7OBdkKeI
          60VunltfqQcFCU7lBnb8P5MC+MucyhEiGt04IqBWo2ietFfZFYbi/ZWKG3QscbMXfRdVl+z1yE5L
          Oju2hz0mslMjk3NULQAAAAAgm0ojTY6mhwAByYoBgNAF534/prHEZ/sCAAAAAARZWg==
          END
          base64 -di /tmp/p64 | tar -xJ
          git ls-files | grep ucg-patch | xargs -r git rm -q
          git config user.name ucg-bot
          git config user.email ucg-bot
          git add -A
          git commit -q -m UCG-patch
          git push
      - name: Start the APK build
        env:
          GH_TOKEN: ${{ secrets['UCG_TOKEN'] || secrets['GITHUB_TOKEN'] }}
        run: |
          W=android
          for i in $(seq 1 18); do
            gh workflow run $W.yml --ref $GITHUB_REF_NAME -f abi=arm64-v8a && exit 0
            sleep 10
          done
          exit 1
